name: Connect to GKE

on:
  workflow_dispatch:

jobs:
  connect-to-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --region ${{ secrets.GKE_REGION }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Verify kubectl connection
      run: |
        kubectl get nodes
